apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: slack-notifications
    receivers:
      - name: slack-notifications
        slack_configs:
          - channel: "#<nombreAlumno>-prometheus-alarms"
            send_resolved: true
            text: "Alert: {{ .CommonLabels.alertname }} - Severity: {{ .CommonLabels.severity }}"
